### ISSUE TITLE
"Enhanced Zoom Desktop" plugin

### ISSUE THREAD

**Issue by igor-liferenko** [compiz-reloaded/compiz-plugins-main#1]
Hi,

There is a mention about "Enhanced Zoom Desktop" plugin here:

[https://github.com/compiz-reloaded/compiz-plugins-main/blob/master/metadata/ezoom.xml.in](https://github.com/compiz-reloaded/compiz-plugins-main/blob/master/metadata/ezoom.xml.in)

but the plugin itself is missing.

Could you please give some guidelines what should be done for implementing this plugin?

**Comment by soreau** [comment]
The plugins are in the src directory. Corresponding metadata is what you're looking at there. See https://github.com/compiz-reloaded/compiz-plugins-main/tree/master/src

**Comment by igor-liferenko** [comment]
Hi Scott,

I'm using debian "stretch" packages on amd64 from this repository:

    http://download.tuxfamily.org/compiz/debian

but this plugin is not present in CCSM. Also, search for "ezoom" in dconf-editor gives no results. As I understood from your words, "ezoom" plugin is already available. So how do I enable it?

Maybe it is necessary to rebuild the debian package from sources with some additional parameters?

Thanks,
Igor

**Comment by igor-liferenko** [comment]
Thanks, I have figured out how to enable this plugin. There are some problems with CCSM.

On Debian stretch amd64 with MATE and compiz installed from packages, I have this CCSM window:

![1](https://cloud.githubusercontent.com/assets/17632935/14008996/f1538250-f1b9-11e5-8e30-a40853a98ab6.png)

There is no "Enhanced Zoom Desktop" plugin. This is why I opened the issue. Afterwards I found out that when I select an entry on the left, e.g. "Accessibility", this plugin appears:

![2](https://cloud.githubusercontent.com/assets/17632935/14009019/3a14f8d4-f1ba-11e5-8e73-39d43dae36bc.png)

Then when we go back to "All", all plugins are displayed. Compare this with the first screenshot:

![3](https://cloud.githubusercontent.com/assets/17632935/14009029/5d80eee0-f1ba-11e5-9ec5-051dc82119cc.png)

There is one more problem: not all plugins have pictures for them:

![4](https://cloud.githubusercontent.com/assets/17632935/14009044/7a1b082e-f1ba-11e5-9fe8-743192d37186.png)

I installed compiz this way:

    wget -q http://download.tuxfamily.org/compiz/apt/key.pub -O- | sudo apt-key add -
    sudo sh -c 'echo deb http://download.tuxfamily.org/compiz/debian stretch main >> /etc/apt/sources.list'
    sudo apt-get update
    sudo apt-get install compiz compiz-mate
    gsettings set org.mate.session.required-components windowmanager compiz
    <reboot>

Igor

**Comment by soreau** [comment]
http://download.tuxfamily.org ia not supported here. Try installing from the source found here on github.

**Comment by XRevan86** [comment]
I'll look it up. Issue will stay closed because bug is not in compiz-plugin-main project.
@igor-liferenko, thanks for letting us know.

**Comment by elgeneralmidi** [comment]
@igor-liferenko, @XRevan86, thanks for the report, fixed with the lastest version of ccsm package.
