### ISSUE TITLE
Feature request: Colorfilter: Option to filter everything (incl. wallpaper and snow)

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz-plugins-main#10]
Feature request: Colorfilter: Option to filter everything (incl. wallpaper and snow)

**Comment by ethus3h** [comment]
Maybe or maybe not filter cursor and wizard; I'm not sure.

**Comment by soreau** [comment]
It's not really feasible to filter gl textures rendered by other plugins, but at least we can allow filtering of any window type.

**Comment by nezumisama** [comment]
I don't know how Compiz works internally, but don't you have the final image that you render as a texture? If not, wouldn't it be possible to (if needed/enabled) do final render to texture and then additional re-render from texture to framebuffer with a shader?
