### ISSUE TITLE
Bug or Feature ?

### ISSUE THREAD

**Issue by arifcatalyst** [compiz-reloaded/compiz-plugins-main#33]
The Opacity plugin makes the whole window transparent when set to 0.
What it should be is that only the background of the window should be altered.
Why even have the 0 value then ? 
It's senseless to make a window fully transparent.

**Comment by ethus3h** [comment]
That's a feature, the opacity plugin changes the opacity of the entire window. To just change the background opacity, there are two options:

- Getting this effect properly requires application support, and this can be a mixed bag.
  - GTK2: The Murrine theme engine can do this, although I think it might need a custom patched GTK and/or cairo?
  - GTK3/Qt5: I think custom themes may be able to do this in GTK3 and Qt5, although I haven't tried it.
  - Others (other versions of GTK/Qt, XUL, plain Xlib, etc.): I don't know of any way to get this effect.
- The "Color Opacity" Compiz plugin tries to fake this effect, although I haven't had much luck with it.

If anyone else knows more, please do share :)

**Comment by arifcatalyst** [comment]
![screenshot_2017-07-21_04-21-29](https://user-images.githubusercontent.com/26674272/28442118-3f6234e8-6dcc-11e7-9b2d-0aa57c5f86d4.png)
 Ricing my Desktop
I have been trying to achieve Mac OsX look.
Only if the opacity plugin wouldn't transparent the foreground elements.

**Comment by soreau** [comment]
@arifcatalyst As ethus3h suggested, there is no way for compiz to know which pixels are text or not. Compiz only deals with windows as complete textures. The application (or toolkit) is in the position to differentiate which pixels which should seem transparent.
