### ISSUE TITLE
Bug with the neg plugin...

### ISSUE THREAD

**Issue by Equipe-ADVL** [compiz-reloaded/compiz-plugins-main#34]
Hello, 

Config -> Debian Jessie + XFCE 4.12
We report a bug when using neg plugin.
By default, if the plugin is activated, the entire screen is in inverted color mode.
And this, whatever the graphics card .... Nvidia or ATI or Intel

This problem did not exist under 0.8.12.x but only since 0.8.14.

**Comment by soreau** [comment]
This should be fixed in git master.
