### ISSUE TITLE
Negative plugin randomly negates windows

### ISSUE THREAD

**Issue by styxxx** [compiz-reloaded/compiz-plugins-main#35]
Hi,

when I enable the negative plugin some windows (and menus, like some submenus of the MATE main menu) are shown with negative colors although I didn't activate the effect for those windows. Seems pretty arbitrary.

I was using an older version of compiz before and it first appeaed with the upgrade to compiz-reloaded. Maybe it's some issue with a configuration file? How can I reset the "memory" for all negated windows if there is such a thing so that all windows appear normal again unless I hit the hot key combination?

**Comment by soreau** [comment]
As with issue #34, this is a bug with neg plugin in 0.8.14, it should be fixed in git.
