### ISSUE TITLE
Feature Request: Implement Vulkan api for broader hardware support and reduced graphical artifacts

### ISSUE THREAD

**Issue by Myrddin-Wyllt** [compiz-reloaded/compiz-plugins-main#39]
I've been fiddling with compiz settings and various plugins attempting to eliminate unwanted artifacts on Ryzen mobile hardware. The artifacts obscure what should be visible with erratic colors, lines, etc. I don't believe the issue is related to screen tearing because of the specificity of the problems.
The issues were with dropdown menus in various programs (i.e., right-click menu, searchbar popups, menubar items). V-Sync being enabled or disabled holds no bearing on this. I've been hesitant to enable fglrx support because its deprecated, and I'm using the amdgpu driver which is quite different. 

This is my rationale for direct Vulkan support. If Vulkan were used instead of EGL/OpenGL, distro&hardware-agnostic functionality could be acheived (i.e., more predictable functionality). Better game support and hardware optimizations would be possible. I'm not suggesting to replace the OpenGL/EGL already in place, but rather, add a Vulkan renderer plugin.
I've taken an interest in Compiz and adding Vulkan api support, but I've no experience in coding something this sophisticated. I'm reading the new Vulkan 1.1 specification now, looking at https://github.com/ilia-glushchenko/VulkanCompositor, https://github.com/swaywm/sway, and https://github.com/swaywm/wlroots. Unfortunately, most of these projects have enough differences compared to compiz that porting their work would prove to be a monumental task.

I can't thank the developers here enough for reviving Compiz!

**Comment by soreau** [comment]
Vulkan in compiz is not likely to happen. It sounds like you are experiencing graphics driver problems. If you haven't already, you can try using DRI2 instead of DRI3 with LIBGL_DISABLE_DRI3=1. Closing this for now but discussion is still open.
